### ISSUE TITLE
[RFC] Porting account_move_csv_import to OCA?

### ISSUE THREAD

**Issue by HaraldPanten** [akretion/account-move-import#12]
Hi @alexis-via 

I was wondering why this module is not in OCA, as it's really useful. Did you plan to move it at any time?

Just asking. THX!

**Comment by rvalyi** [comment]
I'll let Alexis answer, but I think it's one of the many modules we don't have enough time to do all the OCA dance to get it accepted (we already push lots of modules in the OCA). So it's very likely if you rebase/graft it onto some OCA repo and make the effort to bring it to the OCA standards we will accept and help too.

May be the French import formats should be abstracted away and put in an extension module in this case...

**Comment by HaraldPanten** [comment]
Hi Raphaël, THX for your prompt reply.

I know you are one of the most active teams in OCA. Because of that, I was wondering if you proposed this module before and maybe it was not accepted or whatever...

We'll keep that in mind, and we'll let you know if we start the OCA adaptation.

Closing issue.
