### ISSUE TITLE
Partner mapping

### ISSUE THREAD

**Issue by Maurice67205** [akretion/account-move-import#4]
Don't know if it is an issue or not but when integrating a FEC file is there a way to get the partner on the account moves 
For example in the attached file I have C1,C2,F1 as partner that come out of another system
When importing in Odoo this information is not retrieved even if I create a partner C1
Many thanks for your help
Regards
Maurice

**Comment by alexis-via** [comment]
The code that matches partner is here:
https://github.com/akretion/account-move-import/blob/13.0/account_move_csv_import/wizard/import_move.py#L533
The code that builds speeddict is here:
https://github.com/akretion/account-move-import/blob/13.0/account_move_csv_import/wizard/import_move.py#L460
As you can see, this module uses the "ref" field of res.partner to try to match them.
