### ISSUE TITLE
Multi company issue 13.0

### ISSUE THREAD

**Issue by HaraldPanten** [akretion/account-move-import#5]
Hi,

We found an issue when trying to import an account move in a multi company environment.

Journal code is not correctly found so we can not import the .csv file.

We changed `self.env.user.company_id` expressions by `self.env.company_id` in `import_move.py` file and now it's working properly.

👍 

@alexis-via

**Comment by alexis-via** [comment]
@HaraldPanten Which version of Odoo are you talking about? I don't see any self.env.user.company_id in the v14.0 branch...

**Comment by HaraldPanten** [comment]
> @HaraldPanten Which version of Odoo are you talking about? I don't see any self.env.user.company_id in the v14.0 branch...

Sorry @alexis-via I missed the version. The problem is in 13.0.

Let me know if you need more info.

**Comment by alexis-via** [comment]
I just push a commit to branch 13.0. Could you update your code and try again?

**Comment by ValentinVinagre** [comment]
Hi @alexis-via Same errors in v.14.0 😄

**Comment by HaraldPanten** [comment]
Should be OK, yep.

THX @alexis-via . Closing issue
